name: Deploy to Server w/ SSH
on: [push]

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: >-
            -rltgoDzvO
            --exclude='.git'
          REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_SSH_USER }}
          TARGET: /opt/Testing
