name: Deploy to Server w/ SSH
on: 
  push:
    branches: 
      - master

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish app.
        run: dotnet publish -c Release -o ./deployable -r linux-x64 --self-contained true

      - name: Deploy to server.
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: >-
            -rltgoDzvO
          REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_SSH_USER }}
          SOURCE: ./deployable
          TARGET: ${{ secrets.SERVER_DEPLOY_TARGET }}
    
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl restart sans-car-website sans-car-bot
