name: Deploy to Server w/ SSH
on: [push]

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }} 
          known-hosts: 'ignore'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Create Test File
        run: touch example.txt
      - name: Deploy with rsync
        run: rsync -avz . ${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_SSH_HOST }}:/opt/SansCar/

